name: flutter_architecture
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_bloc: 0.7.0
  http: ^0.12.0+1
  rxdart: 0.20.0
  equatable: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
